# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
from matplotlib import pyplot as plt

In [2]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
np.__version__

'1.20.3'

#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [6]:
print('{} bytes'.format(a.size * a.itemsize))

80 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [7]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [8]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [9]:
a = np.arange(10, 50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [10]:
a = a[::-1]
a

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [11]:
a = np.arange(9).reshape((3, 3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [12]:
a = np.array([1, 2, 0, 0, 4, 0])
a.nonzero()

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [13]:
a = np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [14]:
a = np.random.rand(3, 3, 3)
a

array([[[0.98054302, 0.6973639 , 0.56486704],
        [0.28182271, 0.83881459, 0.25876037],
        [0.79829074, 0.03540617, 0.26303015]],

       [[0.63740812, 0.98882165, 0.28110092],
        [0.45957517, 0.6637305 , 0.02496394],
        [0.37067264, 0.46321815, 0.22753034]],

       [[0.97271138, 0.29561653, 0.04219385],
        [0.82916411, 0.97203033, 0.58441267],
        [0.26459976, 0.62252268, 0.65145225]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [15]:
a = np.random.rand(10, 10)
a.max(), a.min()

(0.9798545902912502, 0.0022403696247859095)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [16]:
a = np.random.rand(30)
a, a.mean()

(array([0.49928496, 0.29317727, 0.35596601, 0.04104803, 0.41138719,
        0.90977868, 0.59663162, 0.18964946, 0.15352667, 0.89028666,
        0.17237442, 0.98650055, 0.83476844, 0.82292856, 0.37009065,
        0.96834701, 0.87200163, 0.16411654, 0.26691471, 0.67280667,
        0.93561526, 0.30958287, 0.41643728, 0.6513377 , 0.51999768,
        0.08827727, 0.80252906, 0.65951758, 0.60793454, 0.72574257]),
 0.5396185849802421)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [17]:
a = np.ones((5, 5))
a[1:-1, 1:-1] = 0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [18]:
a = np.pad(a, 1)
a

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

```
nan
False
False
nan
True
False
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [19]:
np.diag(np.arange(1, 5), k=-1)


array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [20]:
a = np.zeros((8, 8))
a[::2, ::2] = 1
a[1::2, 1::2] = 1
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [21]:
a = np.empty((6, 7, 8))
np.unravel_index(100, (6, 7, 8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [22]:
a = np.array([[1, 0], [0, 1]])
np.tile(a, (4, 4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [23]:
a = np.random.rand(5, 5)
a = (a - np.mean(a)) / np.std(a)
a

array([[ 1.70491708, -0.54303235, -1.07620425,  0.67421634, -1.42203696],
       [ 1.19833958, -1.41035487, -0.97943169,  1.52784729, -0.83404979],
       [-0.24124942,  0.53053773, -0.28597401,  0.83836529, -0.96907378],
       [-0.8210044 , -0.83460909,  0.85167685,  1.38495274,  0.58444307],
       [ 1.54534873, -1.1328279 , -0.74318448,  0.27053619,  0.1818521 ]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [24]:
color = np.dtype([('r', np.ubyte),
                  ('g', np.ubyte),
                  ('b', np.ubyte),
                  ('a', np.ubyte)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [25]:
a = np.random.rand(5, 3)
b = np.random.rand(3, 2)
a @ b

array([[1.04154353, 0.71904834],
       [1.34465338, 0.63930531],
       [0.68352882, 0.64209409],
       [1.33807107, 0.78124751],
       [0.28943872, 0.13025952]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [26]:
a = np.random.randint(0, 10, size=20)
a[(a > 3) & (a < 9)] *= -1
a

array([-4,  3,  1,  2, -5,  0,  3,  9, -5,  9,  3, -4,  0,  2, -5, -7, -5,
       -6,  3,  0])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [27]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

```
Z**Z -- OK
2 << Z >> 2 -- OK
Z <- Z -- IDK what was expected really
1j*Z -- haha nice __i__maginary xD
Z/1/1 -- OK
Z<Z>Z -- Dead as expected
```

In [28]:
a = np.random.randint(1, 8, 10)
#a, a < a > a

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

```
np.array(0) / np.array(0) -- NaN
np.array(0) // np.array(0) -- 0
np.array([np.nan]).astype(int).astype(float) -- -2.14748365e+09 ???
```

#### 29. How to round away from zero a float array ? (★☆☆)

In [29]:
a = np.random.uniform(-2, 2, 10)
a, np.copysign(np.ceil(np.abs(a)), a)

(array([ 1.82747963, -0.58337276,  1.51576657, -1.95765714, -1.70533134,
        -1.88126342, -1.41041668,  1.2673704 ,  1.42159078, -0.90879374]),
 array([ 2., -1.,  2., -2., -2., -2., -2.,  2.,  2., -1.]))

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [30]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

In [31]:
_ = np.seterr(**defaults)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [32]:
np.sqrt(-1) == np.emath.sqrt(-1)

/var/folders/gz/9x93f64d11z1jqg8f1z2rgyc0000gn/T/ipykernel_31555/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [33]:
np.datetime64('today') - 1, np.datetime64('today'), np.datetime64('today') + 1 

(numpy.datetime64('2021-10-12'),
 numpy.datetime64('2021-10-13'),
 numpy.datetime64('2021-10-14'))

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [34]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [35]:
# ?

a = np.random.randint(1, 10, (5, 5))
b = np.random.randint(1, 10, (5, 5))
(a + b) * (-a / 2)

array([[-45.5, -20. , -58.5, -20. ,  -8. ],
       [ -7.5, -35. , -27.5, -42. , -25. ],
       [-31.5, -56. , -42. ,  -7. ,  -9. ],
       [-30. ,  -4.5, -48. , -52.5, -12. ],
       [-30. ,  -4. , -52. , -64. , -26. ]])

In [36]:
help(np.floor)

Help on ufunc:

floor = <ufunc 'floor'>
    floor(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Return the floor of the input, element-wise.
    
    The floor of the scalar `x` is the largest integer `i`, such that
    `i <= x`.  It is often denoted as :math:`\lfloor x \rfloor`.
    
    Parameters
    ----------
    x : array_like
        Input data.
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [37]:
a = np.random.rand(2, 2) + np.random.randint(1, 10, (2, 2))
#a = np.array(a, dtype=np.int64)
#a = np.floor(a)
#a = np.trunc(a)
#a = a // 1
#a = a - a % 1

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [38]:
a = np.arange(4)
a = np.tile(a, (4, 1))
a

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [39]:
def generator():
    for i in range(10):
        yield i

a = np.fromiter(generator(), dtype=np.int64)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [40]:
a = np.linspace(0.1, 1, 11)[:-1]

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [41]:
a = np.random.rand(10)
a.sort()
a

array([0.11366142, 0.3353643 , 0.34746547, 0.50805534, 0.65802749,
       0.66909672, 0.71544521, 0.8032524 , 0.85480444, 0.98767891])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [42]:
a = np.arange(4)
np.add.reduce(a)

6

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [43]:
a = np.random.rand(10)
b = np.random.rand(10)
np.array_equal(a, b), (a == b).min()

(False, False)

#### 43. Make an array immutable (read-only) (★★☆)

In [44]:
a = np.random.rand(10)
a.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [45]:
a = np.random.rand(10, 2)
b = np.zeros_like(a)
b[:, 0] = np.sqrt(a[:, 0] ** 2 + a[:, 1] ** 2)
b[:, 1] = np.arctan2(a[:, 0], a[:, 1])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [46]:
a = np.random.randint(1, 10, 10)
a[a.argmax()] = 0

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [47]:
a = np.zeros((10, 10), dtype=[('x', float), ('y', float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0, 1, 10), np.linspace(0, 1, 10))
a

array([[(0.        , 0.        ), (0.11111111, 0.        ),
        (0.22222222, 0.        ), (0.33333333, 0.        ),
        (0.44444444, 0.        ), (0.55555556, 0.        ),
        (0.66666667, 0.        ), (0.77777778, 0.        ),
        (0.88888889, 0.        ), (1.        , 0.        )],
       [(0.        , 0.11111111), (0.11111111, 0.11111111),
        (0.22222222, 0.11111111), (0.33333333, 0.11111111),
        (0.44444444, 0.11111111), (0.55555556, 0.11111111),
        (0.66666667, 0.11111111), (0.77777778, 0.11111111),
        (0.88888889, 0.11111111), (1.        , 0.11111111)],
       [(0.        , 0.22222222), (0.11111111, 0.22222222),
        (0.22222222, 0.22222222), (0.33333333, 0.22222222),
        (0.44444444, 0.22222222), (0.55555556, 0.22222222),
        (0.66666667, 0.22222222), (0.77777778, 0.22222222),
        (0.88888889, 0.22222222), (1.        , 0.22222222)],
       [(0.        , 0.33333333), (0.11111111, 0.33333333),
        (0.22222222, 0.33333333), (0.

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [48]:
# Thx Evgeni Burovski for an awesome task!

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(C)

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [49]:
for dtype in (np.int64, np.int32, np.int16, np.int8, np.int0):
    print(np.iinfo(dtype))
for dtype in (np.float128, np.float64, np.float32, np.float16):
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).min)

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for int16
---------------------------------------------------------------
min = -32768
max = 32767
---------------------------------------------------------------

Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------

1.189731495357231765e+49

#### 49. How to print all the values of an array? (★★☆)

In [56]:
with np.printoptions(threshold=np.inf):
    print(np.linspace(0, 100, 1000))


[  0.           0.1001001    0.2002002    0.3003003    0.4004004
   0.5005005    0.6006006    0.7007007    0.8008008    0.9009009
   1.001001     1.1011011    1.2012012    1.3013013    1.4014014
   1.5015015    1.6016016    1.7017017    1.8018018    1.9019019
   2.002002     2.1021021    2.2022022    2.3023023    2.4024024
   2.5025025    2.6026026    2.7027027    2.8028028    2.9029029
   3.003003     3.1031031    3.2032032    3.3033033    3.4034034
   3.5035035    3.6036036    3.7037037    3.8038038    3.9039039
   4.004004     4.1041041    4.2042042    4.3043043    4.4044044
   4.5045045    4.6046046    4.7047047    4.8048048    4.9049049
   5.00500501   5.10510511   5.20520521   5.30530531   5.40540541
   5.50550551   5.60560561   5.70570571   5.80580581   5.90590591
   6.00600601   6.10610611   6.20620621   6.30630631   6.40640641
   6.50650651   6.60660661   6.70670671   6.80680681   6.90690691
   7.00700701   7.10710711   7.20720721   7.30730731   7.40740741
   7.50750751   7.60

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [59]:
a = np.arange(1, 10)
b = 7.3
a[np.argmin(np.abs(a - b))]

7

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [67]:
# Fix?

mydtype = np.dtype([('x', np.int64),
                  ('y', np.int64),
                  ('r', np.ubyte),
                  ('g', np.ubyte),
                  ('b', np.ubyte)])
a = np.array([(16, 10, 23, 56, 2)], dtype=mydtype)
a

array([(16, 10, 23, 56, 2)],
      dtype=[('x', '<i8'), ('y', '<i8'), ('r', 'u1'), ('g', 'u1'), ('b', 'u1')])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [74]:
# Cool!

c = np.random.random((10, 2))
x, y = np.atleast_2d(c[:, 0], c[:, 1])

dist = np.sqrt((x - x.T)**2 + (y - y.T)**2)
dist

array([[0.        , 0.26419576, 0.944941  , 0.44013203, 0.7557174 ,
        0.83690008, 0.42471311, 0.4945533 , 0.31026136, 0.24124475],
       [0.26419576, 0.        , 0.71391406, 0.23355667, 0.6385485 ,
        0.78257114, 0.25611294, 0.23229511, 0.26866937, 0.39530359],
       [0.944941  , 0.71391406, 0.        , 0.50498211, 0.46897134,
        0.67834005, 0.81618225, 0.56997166, 0.69457881, 0.92518069],
       [0.44013203, 0.23355667, 0.50498211, 0.        , 0.42282426,
        0.59656288, 0.43715639, 0.25354284, 0.22624034, 0.45093954],
       [0.7557174 , 0.6385485 , 0.46897134, 0.42282426, 0.        ,
        0.22063508, 0.85997982, 0.65646366, 0.44550627, 0.62279966],
       [0.83690008, 0.78257114, 0.67834005, 0.59656288, 0.22063508,
        0.        , 1.0246171 , 0.84536199, 0.5411477 , 0.65017188],
       [0.42471311, 0.25611294, 0.81618225, 0.43715639, 0.85997982,
        1.0246171 , 0.        , 0.24666874, 0.52477441, 0.62417815],
       [0.4945533 , 0.23229511, 0.5699716

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? (★★☆)

In [81]:
# Not float32 but idc -- IDK what is in answer...

a = np.random.random((4, 4)) + 1 
a = a.astype(np.int32)
a

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)